### ISSUE TITLE
Mixin apply failed jeepers_shops.mixins.json

### ISSUE THREAD

**Issue by sndmax** [ExcessiveAmountsOfZombies/jEEPersShops#1]
Hello! 
I'm gettings error in a modpack LITV3-1.19.2-Serverpack-2.4, forge 1.19.2-43.3.2
Using jEEPersShops-1.19.2-FORGE-1.0.0.jar

`[main/FATAL] [mixin/]: Mixin apply failed jeepers_shops.mixins.json:ACMAccessor -> net.minecraft.world.inventory.AbstractContainerMenu: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching remoteSlots:Lnet/minecraft/core/NonNullList; in net/minecraft/world/inventory/AbstractContainerMenu for jeepers_shops.mixins.json:ACMAccessor->@Accessor[FIELD_GETTER]::remoteSlots()Lnet/minecraft/core/NonNullList; [INJECT Applicator Phase -> jeepers_shops.mixins.json:ACMAccessor -> Apply Accessors ->  -> Locate -> jeepers_shops.mixins.json:ACMAccessor->@Accessor[FIELD_GETTER]::remoteSlots()Lnet/minecraft/core/NonNullList;]
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching remoteSlots:Lnet/minecraft/core/NonNullList; in net/minecraft/world/inventory/AbstractContainerMenu for jeepers_shops.mixins.json:ACMAccessor->@Accessor[FIELD_GETTER]::remoteSlots()Lnet/minecraft/core/NonNullList; [INJECT Applicator Phase -> jeepers_shops.mixins.json:ACMAccessor -> Apply Accessors ->  -> Locate -> jeepers_shops.mixins.json:ACMAccessor->@Accessor[FIELD_GETTER]::remoteSlots()Lnet/minecraft/core/NonNullList;]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:518) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:501) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:475) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1389) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]`

**Comment by josemunoz18** [comment]
I did a compare with the fabric version and found that It was missing a line in the file jeepers_shops.mixins.json
 
"refmap": "jEEPersShops-refmaps.json"

I modified with the line missing and the mod works!

The original look like:

![image](https://github.com/ExcessiveAmountsOfZombies/jEEPersShops/assets/119136771/c49a2dfc-eda8-462c-a0f0-4a97f243ce49)

And the modified version is:

![image](https://github.com/ExcessiveAmountsOfZombies/jEEPersShops/assets/119136771/8ffa4e8d-c103-45a8-b478-448c10884992)

**Comment by sndmax** [comment]
@josemunoz18 Hey! Can you send working jar?
I checked the jar with issue and the refmap file isnt missing there, recomplining with adding that line not helped too, same error

**Comment by josemunoz18** [comment]
Hi,
I attached the working jar.
There is something important, you must install the mod EightsEconomyP because it has dependency of it.

[jEEPersShops-1.19.2-FORGE-1.0.0.jar.zip](https://github.com/ExcessiveAmountsOfZombies/jEEPersShops/files/13495226/jEEPersShops-1.19.2-FORGE-1.0.0.jar.zip)

**Comment by sndmax** [comment]
It works now, ty! Confirming the problem with the fix above resolved
